paths:
  result_dir: "./results"   
  data_dir: "../REC/corpus"    
  rec_checkpoint_dir: "../REC/checkpoints"  
  model_path: "../REC/model"      
  log_file: "./results/soup.log"      
  pred_dir: "./results/predictions"        

device: "cpu"
gpu: "0"
experiment:
  version: v2
  dataset: "MovieLens_1M"          
  num_devices: 1
  train: true
  evaluate: true
  init_lambda: null
  prune: false
  self_cof: 0.5
  prune_threshold: 0.9
  router_hidden_layers: 1
  num_steps: 20
  batch_size: 5120
  lr: 0.001
  num_batch_per_ray: 1
  alpha: 1    # Dirichlet alpha
  reg_lambda: 0
  window_size: 1
  seed: 42
  save_interval: 5
  num_evaluation_samples: 11

rec:
  path: "../REC/corpus"
  dataset: "MovieLens_1M"
  reader: "SeqReader"
  regenerate: false
  sep: "\t"

data:
  dataset: "MovieLens_1M"
  path: "../REC/corpus"
  sep: "\t"
  regenerate: false

model:
  name: "SASRec"
  emb_size: 64
  num_layers: 1
  num_heads: 4
  hidden_size: 100
  dropout: 0.2
  final_act: "tanh"
  history_max: 20
  use_adapter: false

training:
  all_epoch: 1
  save_epoch: 1
  check_epoch: 1
  test_epoch: 1
  batch_size: 5120
  lr: 0.001
  l2: 0
  early_stop: 5
  save_final_results: 1
  load: 0

testing:
  test_num: 10
  eval_batch_size: 5120

eval:
  topk: [5, 10]
  metric: ["NDCG", "HR", "ALPHA_NDCG"]
  main_metric: "NDCG@10"

accuracy_weight: 0.0
diversity_weight: 1.0
buffer: 1
num_neg: 9
dropout: 0.2
test_all: 0
optimizer: "Adam"
num_workers: 1
pin_memory: 0
train: 0